INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.sitemaps',

    'corsheaders',
    'django_filters',
    'phonenumber_field',
    'drf_yasg',
    'rest_framework',
    'drf_extra_fields',
    'constance',
    'constance.backends.database',
    'ckeditor',
    'ckeditor_uploader',
    'nested_inline',

    'apps.file',
    'apps.chemical_resistance_calc',
    'apps.questionnaires',
    'apps.seo',
    'apps.pages',
    'apps.affiliates',
    'apps.support',
    'apps.mailing_list',
    'apps.catalog',
    'apps.cart',
    'apps.order',
    'apps.application',
]
