# Generated by Django 3.0.2 on 2021-02-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20210214_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireresult',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опроса'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='data',
            new_name='value',
        ),
    ]
