# Generated by Django 3.0.2 on 2021-02-20 10:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20210215_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=jsonfield.fields.JSONField(verbose_name='Ответ на вопрос, в формате json'),
        ),
    ]
