# Generated by Django 3.0.2 on 2021-03-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20210226_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireResult', verbose_name='Результат опроса'),
        ),
    ]
