# Generated by Django 3.0.2 on 2021-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20210301_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordinal_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
