# Generated by Django 3.0.2 on 2021-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_question_text_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresult',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
    ]
