# Generated by Django 3.0.2 on 2021-03-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_questionnaireresult_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='ordinal_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
