# Generated by Django 3.0.2 on 2021-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_resistance_calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofchemicalresistance',
            name='formula',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Формула'),
        ),
    ]
