# Generated by Django 3.0.2 on 2021-06-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_resistance_calc', '0003_auto_20210311_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorcalculationrequest',
            name='chemical_resistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calc_result', to='chemical_resistance_calc.TableOfChemicalResistance'),
        ),
    ]
