# Generated by Django 3.0.2 on 2021-02-20 10:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionForArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
                ('projects', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Список проектов')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='file.File', verbose_name='Иконка')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='file.File', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Решение для областей',
                'verbose_name_plural': 'Решения для областей',
            },
        ),
    ]
