# Generated by Django 3.0.2 on 2021-02-24 08:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionforarea',
            name='projects',
        ),
        migrations.CreateModel(
            name='CompleteProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_project', to='file.File', verbose_name='Фото')),
                ('solution_for_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_projects', to='pages.SolutionForArea', verbose_name='Решение для области')),
            ],
            options={
                'verbose_name': 'Готовый проект',
                'verbose_name_plural': 'Готовые проекты',
            },
        ),
    ]
