# Generated by Django 3.0.2 on 2021-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210224_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionforarea',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
