# Generated by Django 3.0.2 on 2021-03-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('pages', '0003_solutionforarea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionforarea',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_for_area_icon', to='file.File', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='solutionforarea',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_for_area_photo', to='file.File', verbose_name='Главное фото'),
        ),
    ]
