# Generated by Django 3.0.2 on 2021-03-14 11:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('pages', '0004_auto_20210314_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_production_icon', to='file.File', verbose_name='Иконка')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_production_photo', to='file.File', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Подробнее о продукции',
                'verbose_name_plural': 'Подробнее о продукции',
            },
        ),
    ]
