# Generated by Django 3.0.2 on 2021-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduction',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='solutionforarea',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
