# Generated by Django 3.0.2 on 2021-03-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210316_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionforarea',
            name='icon',
        ),
    ]
