# Generated by Django 3.0.2 on 2021-03-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('pages', '0007_remove_solutionforarea_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproduction',
            name='icon',
        ),
        migrations.AddField(
            model_name='aboutproduction',
            name='preview_for_mainpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_production_preview_for_mainpage', to='file.File', verbose_name='Иконка'),
        ),
    ]
