# Generated by Django 3.0.2 on 2021-03-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('pages', '0008_auto_20210317_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduction',
            name='preview_for_mainpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_production_preview_for_mainpage', to='file.File', verbose_name='Превью для главной страницы'),
        ),
    ]
