# Generated by Django 3.0.2 on 2021-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210421_1451'),
        ('pages', '0009_auto_20210317_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionforarea',
            name='products',
            field=models.ManyToManyField(related_name='solution_products', to='catalog.Product', verbose_name='Товары'),
        ),
    ]
