# Generated by Django 3.0.2 on 2021-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
