# Generated by Django 3.0.2 on 2021-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название филиала'),
        ),
    ]
