# Generated by Django 3.0.2 on 2021-06-01 15:52

import apps.affiliates.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0009_auto_20210326_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUseFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('terms_of_use_user', models.FileField(upload_to=apps.affiliates.models.directory_path, verbose_name='Пользовательское соглашение')),
                ('terms_of_use_site', models.FileField(upload_to=apps.affiliates.models.directory_path, verbose_name='Условия пользования сайтом')),
                ('affiliate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_of_use', to='affiliates.Affiliate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
