# Generated by Django 3.0.2 on 2021-08-04 10:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0011_auto_20210621_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='phone_down',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон в подвале'),
        ),
    ]
