# Generated by Django 3.0.2 on 2021-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0012_auto_20210804_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название компании'),
        ),
    ]
