# Generated by Django 3.0.2 on 2021-12-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0013_affiliate_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='work_graphic_office',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='График работы офиса'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='work_graphic_storage',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='График работы склада'),
        ),
    ]
