# Generated by Django 3.0.2 on 2021-12-20 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0014_auto_20211218_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name_requisite', models.CharField(max_length=200, verbose_name='Наименование реквизита филиала')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование реквизита филиала')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('physical_address', models.CharField(max_length=200, verbose_name='Физический адрес')),
                ('ogrn', models.CharField(blank=True, default='', max_length=50, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, default='', max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=50, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, default='', max_length=50, verbose_name='ОКПО')),
                ('okved', models.CharField(blank=True, default='', max_length=50, verbose_name='ОКВЭД')),
                ('okato', models.CharField(blank=True, default='', max_length=50, verbose_name='ОКАТО')),
                ('oktmo', models.CharField(blank=True, default='', max_length=50, verbose_name='ОКТМО')),
                ('okfc', models.CharField(blank=True, default='', max_length=50, verbose_name='ОКФМ')),
                ('payment_account', models.CharField(max_length=250, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=250, verbose_name='Корересподентский счет')),
                ('bik', models.CharField(max_length=50, verbose_name='БИК')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='requisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.Requisite', verbose_name='Реквизиты филиала'),
        ),
    ]
