# Generated by Django 3.0.2 on 2021-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210916_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_company',
            field=models.CharField(default='', max_length=100, verbose_name='Название компании'),
        ),
    ]
