# Generated by Django 3.0.2 on 2021-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_company',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
    ]
