# Generated by Django 3.0.2 on 2021-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('order', '0005_auto_20210930_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requisites',
            field=models.ManyToManyField(blank=True, related_name='requisites', to='file.File', verbose_name='Реквизиты заказчика'),
        ),
    ]
