# Generated by Django 3.0.2 on 2021-02-14 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=256)),
                ('route', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('h1', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=2048)),
                ('keywords', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
