# Generated by Django 3.0.2 on 2021-03-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'seo', 'verbose_name_plural': 'seo'},
        ),
    ]
