# Generated by Django 3.0.2 on 2021-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20210314_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='canonical_rel',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='h1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='route',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.TextField(),
        ),
    ]
