# Generated by Django 3.0.2 on 2022-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20211022_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
