# Generated by Django 3.0.2 on 2021-03-15 17:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('support', '0002_auto_20210314_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_main_photo', to='file.File', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Article', verbose_name='Статья')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_photos', to='file.File', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото статьи',
                'verbose_name_plural': 'Фото статьи',
            },
        ),
    ]
