# Generated by Django 3.0.2 on 2021-03-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('support', '0003_auto_20210315_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlephoto',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_photos', to='support.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_photo', to='file.File', verbose_name='Фото'),
        ),
    ]
