# Generated by Django 3.0.2 on 2021-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20210316_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
