# Generated by Django 3.0.2 on 2021-06-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210609_2152'),
        ('support', '0006_auto_20210322_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='product_catalogs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_catalogs', to='catalog.Catalog', verbose_name='Каталог товаров (для подробного вида)'),
        ),
    ]
