# Generated by Django 3.0.2 on 2021-06-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_catalog_product_catalogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='product_catalogs',
        ),
    ]
