# Generated by Django 3.0.2 on 2021-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_catalog_product_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='ordering_num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
