# Generated by Django 3.0.2 on 2021-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_catalog_ordering_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория каталога', 'verbose_name_plural': 'Категории каталога'},
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядковый номер отображения'),
        ),
    ]
