# Generated by Django 3.0.2 on 2021-12-24 14:30

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=150, verbose_name='Имя отправителя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Пример, +79510549236', max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='Комментрий')),
                ('files', models.ManyToManyField(related_name='files', to='file.File', verbose_name='Файоы')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
