# Generated by Django 3.0.2 on 2021-04-02 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('type', models.CharField(choices=[('float', 'Численный'), ('char', 'Символьный')], max_length=16, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Аттрибут',
                'verbose_name_plural': 'Аттрибуты',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='catalog.Catalog')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('vendor_code', models.CharField(max_length=32, verbose_name='Артикул')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Catalog')),
                ('photos', models.ManyToManyField(related_name='photos_product', to='file.File')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProdAttr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('numeric', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('text', models.CharField(blank=True, max_length=64, null=True, verbose_name='Символьное значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodattrs_attr', to='catalog.Attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodattrs_product', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Продукт-аттрибут',
                'verbose_name_plural': 'Продукты-аттрибуты',
            },
        ),
    ]
