# Generated by Django 3.0.2 on 2021-04-02 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('attrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters_attr', to='catalog.Attribute')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters_catalog', to='catalog.Catalog')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
    ]
