# Generated by Django 3.0.2 on 2021-04-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodattr',
            options={'verbose_name': 'Товар-аттрибут', 'verbose_name_plural': 'Товары-аттрибуты'},
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='attrs',
            new_name='attr',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='catalog.Catalog'),
        ),
    ]
