# Generated by Django 3.0.2 on 2021-04-08 12:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('catalog', '0005_auto_20210407_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calatog_photo', to='file.File'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='show_on_mainpage',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
    ]
