# Generated by Django 3.0.2 on 2021-04-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210408_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Единица измерения'),
        ),
    ]
