# Generated by Django 3.0.2 on 2021-04-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('catalog', '0011_auto_20210415_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='attr',
        ),
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='filter',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.Attribute'),
        ),
        migrations.AddField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('choice', 'выбор'), ('multi_choice', 'мультивыбор'), ('range', 'диапазон')], max_length=14, null=True, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='products', to='file.File', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.Catalog'),
        ),
        migrations.AlterField(
            model_name='prodattr',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Attribute'),
        ),
        migrations.AlterField(
            model_name='prodattr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Полное название'),
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
