# Generated by Django 3.0.2 on 2021-04-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210419_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.Catalog'),
        ),
    ]
