# Generated by Django 3.0.2 on 2021-04-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210425_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Артикул'),
        ),
    ]
