# Generated by Django 3.0.2 on 2021-05-10 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210428_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=32, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=32, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Размерная хакартеристика',
                'verbose_name_plural': 'Размерные характеристики',
            },
        ),
    ]
