# Generated by Django 3.0.2 on 2021-05-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210526_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_text',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Текст в описании'),
        ),
    ]
