# Generated by Django 3.0.2 on 2021-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodattr',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Символьное значение'),
        ),
    ]
