# Generated by Django 3.0.2 on 2021-06-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_catalog_product_catalogs'),
        ('catalog', '0026_product_support_catalogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Полное наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_catalogs',
            field=models.ManyToManyField(related_name='products_support_catalog', to='support.Catalog', verbose_name='Каталоги-файлы, ссылающиеся на этот товар'),
        ),
    ]
