# Generated by Django 3.0.2 on 2021-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20210616_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodattr',
            name='text',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Символьное значение'),
        ),
    ]
