# Generated by Django 3.0.2 on 2021-10-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20210812_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='limitation_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limitation_filters', to='catalog.Filter', verbose_name='Фильтр, от выбора которого будут ограничиваться варианты текущего'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='catalog.Filter', verbose_name='От кого зависит фильтр (родительский фильтр)'),
        ),
    ]
