# Generated by Django 3.0.2 on 2021-10-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20211022_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='limitation_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limitation_filters', to='catalog.Filter', verbose_name='Ограничивающий фильтр, от выбора которого будут фильтроваться варианты текущего фильтра'),
        ),
    ]
