# Generated by Django 3.0.2 on 2021-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20211022_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_in_top',
            field=models.BooleanField(default=False, verbose_name='Отображать на первых страницах каталогов'),
        ),
    ]
