# Generated by Django 3.0.2 on 2021-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_catalog_product_catalogs'),
        ('catalog', '0032_product_display_in_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='support_catalogs',
            field=models.ManyToManyField(blank=True, related_name='products_support_catalog', to='support.Catalog', verbose_name='Каталоги-файлы, ссылающиеся на этот товар'),
        ),
    ]
