# Generated by Django 3.0.2 on 2021-11-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20211103_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_in_top',
        ),
        migrations.AddField(
            model_name='product',
            name='display_in_top_in_child',
            field=models.BooleanField(default=False, verbose_name='Отображать товар в топе, в каталоге второго уровня'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_in_top_in_parent',
            field=models.BooleanField(default=False, verbose_name='Отображать товар в топе, в каталоге первого уровня'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_in_top_wo_catalog',
            field=models.BooleanField(default=False, verbose_name='Отображать товар в топе, без выбранного каталога'),
        ),
    ]
