# Generated by Django 3.0.2 on 2021-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20211105_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='ordering_num',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
