# Generated by Django 3.0.2 on 2022-01-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_catalog_ordering_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='limitation_filter',
        ),
        migrations.AddField(
            model_name='filter',
            name='limitation_filters',
            field=models.ManyToManyField(blank=True, related_name='_filter_limitation_filters_+', to='catalog.Filter', verbose_name='Ограничивающие фильтры, от выбора которых будут фильтроваться варианты текущего фильтра'),
        ),
    ]
