# Generated by Django 3.0.2 on 2022-01-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20220111_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='limitation_filters',
        ),
        migrations.AddField(
            model_name='filter',
            name='limitation_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limitation_filters', to='catalog.Filter', verbose_name='Ограничивающий фильтр, от выбора которого будут фильтроваться варианты текущего фильтра'),
        ),
    ]
