# Generated by Django 3.0.2 on 2022-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20220121_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodattr',
            name='text_translit',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Транслит'),
        ),
    ]
